### ISSUE TITLE
Finding PowerPal bluetooth address

### ISSUE THREAD

**Issue by dogmachine** [WeekendWarrior1/powerpal_ble#2]
G'day mate,

Thanks for your great work, I have gotten this going and it is working a treat.

For the benefit of others, I just wanted to point out that unlike your example esphome yaml skeleton, my powerpal lives in a bluetooth address space of F9:D1:0F:00:00:00 rather than the DF:5C:55:00:00:00 address space mentioned.

If you are another punter like me trying to get this to work, and your powerpal does not have the bluetooth address listed on the device or on the packaging, an easy way to find it is to stand near the powerpal with an android phone and add a new bluetooth device.  You'll see "powerpal-somethingblahblah" appear.  Connect to it, and then once that is completed, view the connection.  The bluetooth address is listed.

Additionally, if your computer is close enough to the powerpal, just flash the esp32 with this repo's code and the esp32's local console will display blue output from "esp32_ble_tracker" which will list detected bluetooth addresses.  My computers were nowhere near the PowerPal, so I found using an android phone easier.

Once again, thanks for making available your work so the rest of us could enjoy it, you're a top bloke.

Cheers.

**Comment by dogmachine** [comment]
Wasn't really an issue, just no wiki, and wanted to leave breadcrumbs for others.

**Comment by michaelblight** [comment]
Adding to this, the nRF Connect app will not list the MAC Address on iPhones. Also, I was using an M5Stamp which doesn't cope well switching between Wifi and Bluetooth, but the code below worked for me. Don't forget you need the Powerpal to be advertising, so nothing should be actively connected to it (ie. turn off bluetooth and kill the app).
```
api:
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

esp32_ble_tracker:
  scan_parameters:
    continuous: False
    active: True
    interval: 320ms
    window: 300ms
  on_ble_advertise:
    then:
      - lambda: |-
          if (strcmp(x.get_name().c_str(), "") != 0) {
            ESP_LOGI("mb_ble_adv", "Name: %s Address: %s", x.get_name().c_str(), x.address_str().c_str());
          }
```
